### ISSUE TITLE
Add capture support

### ISSUE THREAD

**Issue by ortutay** [timmh/react-native-camera#1]
As mentioned [here](https://github.com/lwansbrough/react-native-camera/issues/87#issuecomment-146672648), this lacks capture support. Capture is probably the most useful camera feature :).

Do you have an idea of where I should start looking to get this to work? I can try to take a crack at it

**Comment by timmh** [comment]
You are right, capture would be useful :D
If you want to implement picture capture yourself, take a look at the the [android documentation](http://developer.android.com/reference/android/hardware/Camera.html#takePicture%28android.hardware.Camera.ShutterCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback, android.hardware.Camera.PictureCallback%29), you should be able to call that method in `ReactCameraView.java`.
Video capture looks a little more complicated.

**Comment by timmh** [comment]
Basic capture support now working: #3
