### ISSUE TITLE
Can't draw anything on top of it

### ISSUE THREAD

**Issue by WellDone2094** [timmh/react-native-camera#10]
i'm trying to put some element on top of the camera preview but the camera cover everything. This is my code:

```
<View style={{flex: 1}}>
   <Camera style={{flex: 1}}></Camera>
   <View style={{position: 'absolute', width: 200, height: 200, backgroundColor: '#FFF'}}>
       <Text> TEST </Text>
   </View>
</View>
```

**Comment by timmh** [comment]
This seems to be an issue with your styling, not with the camera component itself.
Please take a look at the example which has buttons covering the camera.
