### ISSUE TITLE
Android support for RN 0.16

### ISSUE THREAD

**Issue by teaegg** [timmh/react-native-camera#14]

**Comment by LaurentSouchet-Orange** [comment]
Hi,
I've encourter an error when I used 0.16 version with PropTypes.

![screenshot_20151211-115753](https://cloud.githubusercontent.com/assets/11571061/11742281/e378db60-9ffe-11e5-92b4-589d23296b0a.png)

**Comment by LaurentSouchet-Orange** [comment]
The solution is explained here : https://github.com/facebook/react-native/issues/4605

**Comment by dcy0701** [comment]
@eiriksm many thanks!
