### ISSUE TITLE
Add captureTarget prop

### ISSUE THREAD

**Issue by guillaumemorin** [timmh/react-native-camera#8]
Hi @timmh ,

First of all, thank you very much for your hard work, it's working fine !!

I was wondering if it could be possible to add the captureTarget prop like in the IOS react-native-camera repo (https://github.com/lwansbrough/react-native-camera#capturetarget) instead of just returning Base64 encoded image.

I think it could be a nice and useful improvment but I don't really know where to add this by myself...Do you think this is something that you could add easily ? 

Thanks in advance!
Guillaume

**Comment by timmh** [comment]
Hi @guillaumemorin,
happy to hear that this is somewhat working for you, despite a ton of features missing.
I am already working on a captureTarget prop with support for the two targets supported by the original project.
Thank you for your report as this helps prioritizing the work!

**Comment by guillaumemorin** [comment]
Great @timmh, thanks a lot! I'm definitely waiting for this feature! I've also noticed that it seems to be something wrong with the orientation (https://github.com/lwansbrough/react-native-camera#orientation) when picture is taken: phone is on portrait position and taken picture is rendered on landscape position. Do I miss something ? Do you want I open another issue for this ?

**Comment by timmh** [comment]
Hi @guillaumemorin,
I just pushed the development branch which adds the captureTarget prop (set it to "cameraRoll" to save to the gallery) and fixes the orientation issue for pictures taken in portrait modes (still orientation issues for landscape modes). Please let me know if it works for you.

**Comment by guillaumemorin** [comment]
Hi @timmh,
It seems that there is a problem on my side. When I take a picture, i'm receiving an error:

takePicture failed
native_takePicture
Camera.java: -2
takePicture
Camera.java: 1434

Do you know what it could be ?

**Comment by timmh** [comment]
Hi @guillaumemorin,
unfortunately I am not able to reproduce this issue, could you post logcat logs (for example via [pidcat](https://github.com/JakeWharton/pidcat)) in a new issue?
